### ISSUE TITLE
Grief Prevention plugin support

### ISSUE THREAD

**Issue by CorporalBruno** [DenizenScript/Depenizen-For-Bukkit#100]
#I would like to reference a few things using depenizen and grief prevention.

- [ ] A tag to know How many claim blocks a player has in use, in reserve, and total.
- [x] How many claims a player has.
- [x] The locations of each claim a player has.
- [x] A tag to treat a claim like a cuboid.
- [x] A tag to know the total blocks of each claim.
- [ ] List the players who are trusted on a claim and their levels of trust, and allow manipulation of that via adjust.
- [ ] Ability to modify those levels of access and the players with access using denizen/depenizen. There are currently permissiontrust, accesstrust, containertrust, and trust (build/break).
- [ ] Ability to adjust a players total claim blocks via depenizen/denizen. (add,remove,set)
- [ ] Ability to abandon/delete claims with denizen/depenizen (Thx @GravityX )
- [x] Transferring claims/setting new owner (Thx @GravityX )
- [ ] New Event to listen for a player claiming, deleting/abandoning a claim,
- [x] New Event for when a player enters a grief prevention claim.

Thanks again for all of your hard work folks.

**Comment by mcmonkey4eva** [comment]
```
[16:28:17] <irbDylan> GriefPrevention tags? Yessss +1
[16:28:35] <irbDylan> That'd be awesome, I'd use them.
```

**Comment by Fortifier42** [comment]
I'll get started I guess

**Comment by GravityX** [comment]
Some things I'd suggest if they're easy:
Ability to delete claims with denizen/depenizen
Transferring claims/setting new owner

**Comment by Fortifier42** [comment]
> Ability to modify those levels of access and the players with access using denizen/depenizen.
> Ability to adjust claim blocks via depenizen/denizen.

@GravityX

**Comment by Fortifier42** [comment]
Half done. Will need to add all the metadocs and will update with more content soon :)

**Comment by CorporalBruno** [comment]
i updated some things, again if i did things wrong sorry im so noob. but the updated list has more precise requests especially after playing with the first update and using the tags in place. This will work wonderfully and does so far no glitches found. Thanks Thanks Thanks.

**Comment by Fortifier42** [comment]
Can already adjust owner. !mechamism cpclaim.owner

**Comment by Fortifier42** [comment]
In regards to events, we are very limited to only what grief prevention a provides us, will take a look when I get time or @Morphan1 can

**Comment by mcmonkey4eva** [comment]
@Fortifier42 you forgot meta in places and mislabeled things. You have `griefprotection` instead of `griefprevention` as tags for example.

**Comment by Fortifier42** [comment]
Oh :/ I thought I replaced all those :(

**Comment by Fortifier42** [comment]
> A tag to know the total blocks of each claim.
`<gpclaim@gpclaim.cuboid.blocks.size>` will return the size of the claim in blocks. (Was already implemented.

Only events which are in GriefPrevention which are related to the claims:
- Claim Deleted
- Claim expired

**Comment by CorporalBruno** [comment]
I updated the events idea due to more knowledge about the area.

**Comment by CorporalBruno** [comment]
I'd like to add a new event to depenizen listening for players entering grief prevention claims
- on player enters gpclaim:

**Comment by Fortifier42** [comment]
Yeah - go ask the dev... :/

**Comment by mcmonkey4eva** [comment]
@Fortifier42 that one can definitely be added by us 0.o

**Comment by Fortifier42** [comment]
@mcmonkey4eva then u do it, I'm busy >:(

**Comment by mcmonkey4eva** [comment]
Added meself ya lazy nub

**Comment by Fortifier42** [comment]
I only turned my computer on for the first time last night @mcmonkey4eva D:

**Comment by mcmonkey4eva** [comment]
Consider turning it on more often.

**Comment by Morphan1** [comment]
What still needs to be done here? Removing @Fortifier42 because he died
