### ISSUE TITLE
Some suggestions about MythicMobs and Quests2

### ISSUE THREAD

**Issue by MrMaleficus** [DenizenScript/Depenizen-For-Bukkit#104]
Hello,

That would be a good thing to have more hooks with MytficsMobs and some tags with Quests2.
Instead of using "on mythicmob death" event it would be better to use the event "on player kill entity" by replacing directly the entity with the config name of the mythic mob

In Quests2, just adding the tag <player.quests.points> returning how many Quests Points the player have :) it can be good for a reputation system about NPCs and stuff :)

Thank you for your hard work :+1:

**Comment by Fortifier42** [comment]
The event suggestion is impossible as that is a Denizen event, and would require doubling up on the event into Depenizen too, I've added the ability to specify the mythicmob in the "on mythicmob death" event and I'm working on the quests stuff :)
