### ISSUE TITLE
Skillapi tags and event

### ISSUE THREAD

**Issue by drAkeTool** [DenizenScript/Depenizen-For-Bukkit#105]
Hello I would like to comment on some things I've noticed with skillapi

event:
"on player levels up in skillapi"
commands within the event runs 2 times
http://mcmonkey.org/paste/30184

Tags:
all flags with this syntax `[<class>] ` I can't get the value
```
<player.skillapi.class_level[<player.skillapi.main_class>]>
<player.skillapi.class_level[Vampiro]>
```
http://mcmonkey.org/paste/30185

thank you very much for the effort and attention
good day

Denizen 1601
Depenizen 262
Skillapi v3.37

**Comment by Morphan1** [comment]
Do you use the `/reload` command? That's the only thing I can think of at the moment that would cause the first thing, and I would recommend never using that command, ever.

As for the tag error, are you sure the player is in that class? I can fix the big wall of angry text that it threw at you, but it still wouldn't return anything.

**Comment by drAkeTool** [comment]
watch the video, maybe it will help more
https://dl.dropboxusercontent.com/s/k2qyy5h4ann6e3s/video2.mp4

**Comment by Morphan1** [comment]
Okay, I fixed the tags. SkillAPI has a weirdly setup API for something that's made explicitly to be an API.

Anyways, I still can't see why the event would fire twice. Maybe @mcmonkey4eva can see some weird problem I created somewhere? Or maybe you have 2 .jar's of something somewhere? I don't even

**Comment by Fortifier42** [comment]
@Morphan1 Maybe multiple skills are being leveled up from the command. 

@drAkeTool recommend checking `<context.skill>` and confirming they are the same skill :)

**Comment by Morphan1** [comment]
@Fortifier42 you mean multiple classes? *context.class?

**Comment by Fortifier42** [comment]
Uh, yeah that one...

**Comment by drAkeTool** [comment]
@Fortifier42 
but I'm not going up a skill, the event is level

`    on player levels up in skillapi:
    - narrate "hi <context.level>"`


http://mcmonkey.org/paste/30256

**Comment by Fortifier42** [comment]
Check the class being leveled up though!

**Comment by drAkeTool** [comment]
![bug skillapi](https://cloud.githubusercontent.com/assets/6490373/13025598/df803fea-d1d0-11e5-9ac1-4af71065b4ce.jpg)

`    on player levels up in skillapi:
    - narrate "hi <context.level>"
    - narrate "<context.class>"`

**Comment by Fortifier42** [comment]
It's conflicting with another event... @Morphan1

**Comment by Fortifier42** [comment]
This will be fixed once Denizen is updated :)

**Comment by Fortifier42** [comment]
We've had a few issues with conflicting events. As such we've decided to rewrite the way the skillapi events function, in the coming day(s) you can expect to see the meta on the events to change along with the way they are written, they will now the written as "on skillapi player XX" rather than "on player XX in skillapi".

**Comment by drAkeTool** [comment]
thank you very much for the effort you make
It is much appreciated

**Comment by Fortifier42** [comment]
The events have been fixed as of today. Please come onto the IRC and review the new events, or they can be found on mcmonkey's site. http://mcmonkey.org/denizen/evts/skillapi

**Comment by Morphan1** [comment]
@drAkeTool Sorry about the issues by the way, we don't/can't really test most of the things we add :disappointed:
We're now at 26 supported plugins and the list keeps growing, it'd be chaos to try to test absolutely everything. The best we can do is hope friendly people like you give us some feedback if something goes wrong somewhere. So, really, thank you! :smile:

**Comment by Fortifier42** [comment]
Much love - The DenizenScript team :heart:

**Comment by drAkeTool** [comment]
@Morphan1 No problem, I'm glad to know I can help in the search of some bugs
@Fortifier42 The skillapi events work correctly

thank you very much to all for the excellent support
