### ISSUE TITLE
MobArena Flags

### ISSUE THREAD

**Issue by drAkeTool** [DenizenScript/Depenizen-For-Bukkit#108]
the flags of statistics do not work
`<player.mobarena.stats[Horokan].last_wave>`

"Horokan" is the name of my arena
http://mcmonkey.org/paste/30542

**Comment by Fortifier42** [comment]
I'll take a quick look

**Comment by Fortifier42** [comment]
I see no reason for this error... The API is very lacking in this area, so I had to make do with what I had.. I'll do some testing.

**Comment by Fortifier42** [comment]
Seems to be that MobArena sucks.. D: Not a heap I can do here, I can try file an issue with the developer.

**Comment by drAkeTool** [comment]
thanks for revising

**Comment by Morphan1** [comment]
I'm going to close this. If it's still an issue, please respond with an updated error paste
