### ISSUE TITLE
More Heroes hooking

### ISSUE THREAD

**Issue by MrMaleficus** [DenizenScript/Depenizen-For-Bukkit#109]
Hello ! :)

It would be nice to add more support about heroes tags, events and mechanisms, in order to read and interact with more data in some scripts :) like:

tags:
```
<pl.hero.mana>
<pl.hero.max_mana>
<pl.hero.is_using_skill>
<pl.hero.skills> (returns the list of skills the hero has access to)
```

~~events:
`on hero gains exp:`~~ This is already implemented?

mechanisms:
Heroes dObjects:
- hero_mana
- ~~hero_class~~ Was already implemented?
- hero_prof

Thank you ! :)

**Comment by Morphan1** [comment]
By "is_using_skill" do you mean delayed skills only? As in, they're preparing to use a skill? There's not really anything I can check otherwise

**Comment by MrMaleficus** [comment]
Yes :) In the using the delayed skills.
