### ISSUE TITLE
Error with Jobs

### ISSUE THREAD

**Issue by CKMartens** [DenizenScript/Depenizen-For-Bukkit#110]
I try to use in a Denizen-Script the Job Command
jobs join [<job>]
I have Denizen 0.9.8 r2, Depenizen Build #315, Jobs Reborn 3.3.7 and Spigoot 1.9.4 installed.

After i execute the Script these error comes up:
 
08:18:39 CONSOLE: [INFO] Queue 'TESTSCRIPT_VegetableDozenBbc' Executing: JOBS "join"
08:18:39 CONSOLE: "Zauberer" "player:jail_officer"
08:18:39 CONSOLE: [INFO] +- Executing dCommand: JOBS/p@jail_officer ---------+
08:18:39 CONSOLE: [INFO] ...replacing the linked player with jail_officer
08:18:39 CONSOLE: [INFO] ERROR in script 'TESTSCRIPT'! Woah!! An exception has been
08:18:39 CONSOLE: called with this command!
08:18:39 CONSOLE: [INFO] ERROR in script 'TESTSCRIPT'! Internal exception was thrown!
08:18:39 CONSOLE: WARN]: java.lang.NullPointerException
08:18:39 CONSOLE: WARN]: at net.gnomeffinway.depenizen.commands.JobsCommands.execute(JobsCommands.java:93)
08:18:39 CONSOLE: WARN]: at net.aufdemrand.denizencore.scripts.commands.CommandExecuter.execute(CommandExecuter.java:248)
08:18:39 CONSOLE: WARN]: at net.aufdemrand.denizencore.scripts.queues.ScriptEngine.revolve(ScriptEngine.java:54)
08:18:39 CONSOLE: WARN]: at net.aufdemrand.denizencore.scripts.queues.ScriptQueue.revolve(ScriptQueue.java:677)
08:18:39 CONSOLE: WARN]: at net.aufdemrand.denizencore.scripts.queues.core.TimedQueue.access$000(TimedQueue.java:12)
08:18:39 CONSOLE: WARN]: at net.aufdemrand.denizencore.scripts.queues.core.TimedQueue$1.run(TimedQueue.java:154)
08:18:39 CONSOLE: WARN]: at net.aufdemrand.denizencore.utilities.scheduling.RepeatingSchedulable.tick(RepeatingSchedulable.java:20)
08:18:39 CONSOLE: WARN]: at net.aufdemrand.denizencore.DenizenCore.tick(DenizenCore.java:155)
08:18:39 CONSOLE: WARN]: at net.aufdemrand.denizen.Denizen$2.run(Denizen.java:899)
08:18:39 CONSOLE: WARN]: at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftTask.run(CraftTask.java:71)
08:18:39 CONSOLE: WARN]: at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
08:18:39 CONSOLE: WARN]: at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:734)
08:18:39 CONSOLE: WARN]: at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:399)
08:18:39 CONSOLE: WARN]: at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:665)
08:18:39 CONSOLE: WARN]: at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:564)
08:18:39 CONSOLE: WARN]: at java.lang.Thread.run(Thread.java:745)
08:18:39 CONSOLE: [INFO] +> [Denizen] (Attempted: JOBS "join" "Zauberer"
08:18:39 CONSOLE: "player:jail_officer")

**Comment by Fortifier42** [comment]
This is caused by not having a player attached to the queue. "player:jail_officer" is not correct syntax.

Recommended you watch this video:
[The Player and NPC Arguments](http://mcmonkey.org/denizen/vids/The%20Player%20and%20NPC%20Arguments)

Fixed NPE when player is invalid.
https://github.com/DenizenScript/Depenizen-For-Bukkit/commit/c6364253274fc36822edf595fa37feed3c43b067

**Comment by CKMartens** [comment]
Ok...but if i write
- jobs join Zauberer player:p@jail_officer
or
- jobs join Zauberer player:p@<player.name>
the same error is comming up:

13:14:00 CONSOLE: [INFO] +- Executing dCommand: JOBS/p@jail_officer ---------+
13:14:00 CONSOLE: [INFO] ...replacing the linked player with p@jail_officer
13:14:00 CONSOLE: [INFO] ERROR in script 'TESTSCRIPT'! Woah!! An exception has been
13:14:00 CONSOLE: called with this command!
13:14:00 CONSOLE: [INFO] ERROR in script 'TESTSCRIPT'! Internal exception was thrown!
13:14:00 CONSOLE: WARN]: java.lang.NullPointerException
13:14:00 CONSOLE: WARN]: at net.gnomeffinway.depenizen.commands.JobsCommands.execute(JobsCommands.java:93)
13:14:00 CONSOLE: WARN]: at net.aufdemrand.denizencore.scripts.commands.CommandExecuter.execute(CommandExecuter.java:248)
13:14:00 CONSOLE: WARN]: at net.aufdemrand.denizencore.scripts.queues.ScriptEngine.revolve(ScriptEngine.java:54)
13:14:00 CONSOLE: WARN]: at net.aufdemrand.denizencore.scripts.queues.ScriptQueue.revolve(ScriptQueue.java:677)
13:14:00 CONSOLE: WARN]: at net.aufdemrand.denizencore.scripts.queues.core.TimedQueue.access$000(TimedQueue.java:12)
13:14:00 CONSOLE: WARN]: at net.aufdemrand.denizencore.scripts.queues.core.TimedQueue$1.run(TimedQueue.java:154)
13:14:00 CONSOLE: WARN]: at net.aufdemrand.denizencore.utilities.scheduling.RepeatingSchedulable.tick(RepeatingSchedulable.java:20)
13:14:00 CONSOLE: WARN]: at net.aufdemrand.denizencore.DenizenCore.tick(DenizenCore.java:155)
13:14:00 CONSOLE: WARN]: at net.aufdemrand.denizen.Denizen$2.run(Denizen.java:899)
13:14:00 CONSOLE: WARN]: at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftTask.run(CraftTask.java:71)
13:14:00 CONSOLE: WARN]: at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
13:14:00 CONSOLE: WARN]: at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:734)
13:14:00 CONSOLE: WARN]: at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:399)
13:14:00 CONSOLE: WARN]: at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:665)
13:14:00 CONSOLE: WARN]: at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:564)
13:14:00 CONSOLE: WARN]: at java.lang.Thread.run(Thread.java:745)
13:14:00 CONSOLE: [INFO] +> [Denizen] (Attempted: JOBS "join" "Zauberer"
13:14:00 CONSOLE: "player:p@jail_officer")
13:14:00 CONSOLE: [INFO] +---------------------+

**Comment by Fortifier42** [comment]
Did you try the new build?
http://ci.citizensnpcs.co/job/Depenizen/316/

**Comment by CKMartens** [comment]
Ok thx,

work with the new build
