### ISSUE TITLE
Residence support

### ISSUE THREAD

**Issue by Oruss7** [DenizenScript/Depenizen-For-Bukkit#112]
Hi mcmonkey or Fortifier42  !

It's is possible to hook with https://www.spigotmc.org/resources/residence-1-7-10-up-to-1-10.11480/ plugin please ?

It's an amazing plugin (always in dev) to protect area like a worldguard. 

I use it since 2 years and hope depenizen can add:

- [ ] player enter residence
- [x] location.is_residence
- [x] residence.owner

Thanks you !

(PS: the developer is stilling available on spigot discussion page, not irl, not github)

**Comment by Oruss7** [comment]
Is in dev?

**Comment by Morphan1** [comment]
It... doesn't look like @Fortifier42 ever added this, yet 2 boxes have been checked?.. I guess I'll add them now

**Comment by Fortifier42** [comment]
Think this was in my latest PR...
