### ISSUE TITLE
Issue with Factions 2.8.19 and 2.8.20

### ISSUE THREAD

**Issue by Cyborax** [DenizenScript/Depenizen-For-Bukkit#115]
[15:04:53 INFO]: ERROR! Internal exception was thrown!

15:04:53 WARN: at sun.reflect.GeneratedMethodAccessor169.invoke(Unknown Source)
15:04:53 WARN: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
15:04:53 WARN: at java.lang.reflect.Method.invoke(Method.java:497)
15:04:53 WARN: at net.aufdemrand.denizencore.objects.properties.PropertyParser.getProperties(PropertyParser.java:87)
15:04:53 WARN: at net.aufdemrand.denizen.objects.dNPC.getAttribute(dNPC.java:1076)
15:04:53 WARN: at net.aufdemrand.denizen.tags.core.NPCTags.npcTags(NPCTags.java:81)
15:04:53 WARN: at sun.reflect.GeneratedMethodAccessor86.invoke(Unknown Source)
15:04:53 WARN: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
15:04:53 WARN: at java.lang.reflect.Method.invoke(Method.java:497)
15:04:53 WARN: at net.aufdemrand.denizencore.tags.TagManager.fireEvent(TagManager.java:83)
15:04:53 WARN: at net.aufdemrand.denizencore.tags.TagManager$1.run(TagManager.java:258)
15:04:53 WARN: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
15:04:53 WARN: at java.util.concurrent.FutureTask.run(FutureTask.java:266)
15:04:53 WARN: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
15:04:53 WARN: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
15:04:53 WARN: at java.lang.Thread.run(Thread.java:745)
15:04:53 WARN: Caused by: java.lang.NoSuchMethodError: com.massivecraft.factions.entity.MPlayerColl.create(Ljava/lang/Object;)Ljava/lang/Object;
15:04:53 WARN: at net.gnomeffinway.depenizen.extensions.factions.FactionsPlayerNPCExtension.(FactionsPlayerNPCExtension.java:41)
15:04:53 WARN: at net.gnomeffinway.depenizen.extensions.factions.FactionsPlayerNPCExtension.getFrom(FactionsPlayerNPCExtension.java:26)
15:04:53 WARN: ... 16 more

this error occours if i enable

Faction 2.8.19
MassiveCore 2.8.19
FactionsDynmap 2.8.19
Factions Tax 2.8.19 and only if i also /denizen debug enabled with 2.8.20 its the same.

**Comment by mcmonkey4eva** [comment]
Depenizen is still built against 2.8.2

Perhaps it's time for an update to that, @Morphan1 ?

**Comment by Cyborax** [comment]
Should i change the Timeouttime? i have the following setting:

Socket:
  Enabled: true
  Ip address: 192.168.178.22
  Port: 25560
  Password: Something
  # The name to connect with. Used for the Bungee dServer object.
  # This does not have to be the same name that Bungee itself
  # recognizes, but it is recommended to use that for consistency.
  Name: spawn
  # The time in milliseconds that this server should take while
  # trying to connect to the BungeeCord Socket before giving up.
  # Set this to 0 to try to connect until there's an error
  Timeout: 0
  # The time in milliseconds to wait between attempts at reconnecting
  # to the socket
  Reconnect Delay: 10000

**Comment by mcmonkey4eva** [comment]
That's unrelated Bungee config.  Your best bet is to come into the IRC and bug @Morphan1 about it a fair bit.

Or just downgrade to Factions 2.8.2-ish if you just want quick compatibility.

**Comment by Morphan1** [comment]
Try the latest build

**Comment by Morphan1** [comment]
Assuming this is fixed... Please respond if it is not (with whatever new error it gives) and we'll reopen the issue
