### ISSUE TITLE
Issue with Faction 

### ISSUE THREAD

**Issue by Cyborax** [DenizenScript/Depenizen-For-Bukkit#118]
With Denizen devbuild 21 i have the issue with Faction again. This was already fixed with depenizen 322 and denizen build #1621
http://ci.citizensnpcs.co/job/Denizen_Developmental/21/

http://one.denizenscript.com/paste/36438

**Comment by mcmonkey4eva** [comment]
Where did you get the idea this is a Depenizen issue? Or related to Factions? 0.o

Please post this under the Denizen issues page.
