### ISSUE TITLE
dtlTraders hook

### ISSUE THREAD

**Issue by Xanusek** [DenizenScript/Depenizen-For-Bukkit#119]
Hello.
A command like "dtlTraders [npc] [open/close]" that would open trade gui for selected NPC using dtlTraders.
If [npc] would be blank, it takes the NPC from assignment.
OR NOT (npc tag may not exist for me tbh, it's an idea for full compatibility).

Nothing more i guess, 

Link to plugin:
https://dev.bukkit.org/bukkit-plugins/dtltraders/

Regards!

**Comment by Morphan1** [comment]
There was actually meant to be Denizen support in dtlTraders itself, but @dandielo diededed before finishing everything up 😢
So I just moved (and slightly modified) the code from the plugin into Depenizen and made it register.
`trader [open/close] ({buy}/sell) ({stock}/relation)`
For more information, check monkeybot or the meta site

**Comment by Dandielo** [comment]
Even when I've stopped working on it I'm still aware what's going on there :P Thanks Morphan1 :)
