### ISSUE TITLE
Towny Assistant tag

### ISSUE THREAD

**Issue by teateatea** [DenizenScript/Depenizen-For-Bukkit#120]
Hi there!

Would you be able to add an assistants tag to Depenizen? I asked on the denizen IRC and mcmonkey pointed me here.

There IS already the <town@town.mayor> tag. Something like <player.townyrank> would be great, or a <town@town.assistants> list.

I'm not really sure how this would work with the custom ranks, but those seem extra niche to me.

As always, thank you for creating Depenizen!
Tea

**Comment by Morphan1** [comment]
Added the following tags:
```
<p@player.nation_ranks> - dList of player's nation ranks
<p@player.town_ranks> - dList of player's town ranks
<nation@nation.assistants> - dList(dPlayer) of nation's assistants
<nation@nation.residents> - dList(dPlayer) of nation's residents
<town@town.assistants> - dList(dPlayer) of town's assistants
<town@town.residents> - dList(dPlayer) of town's residents
```

**Comment by teateatea** [comment]
Holy you work fast. Thank you very much!
