### ISSUE TITLE
depenizen region.member

### ISSUE THREAD

**Issue by Cyborax** [DenizenScript/Depenizen-For-Bukkit#121]
Hello there,

i have an issue to get the members of a region.
i had a script that worked with the following command
```
<player.location.regions.get[1].owners.get[1].name>worked before the update
<player.location.regions> is still working

<player.location.regions.members> dont work
<player.location.region.members> dont work
<player.location.regions.owners> dont work
<player.location.region.owners> dont work
```
Thank you for your support!

**Comment by mcmonkey4eva** [comment]
you dropped the `.get[1]` from those tags.

**Comment by Cyborax** [comment]
ow sorry for that.. just .name does not work ok my fail

**Comment by Cyborax** [comment]
sorry uuid in regions was not updated.
now also .name work proper
