### ISSUE TITLE
Survival Games

### ISSUE THREAD

**Issue by bananoke** [DenizenScript/Depenizen-For-Bukkit#25]
Hej guys i was wondering if you will be able to add survival games support for depnizen.
Its dosent matter with plugin would u chose, i just wondering if there will be way to chose "start game" as trigger. Please let me know if you could do that. Thanks for your work - becouse of u minecraft servers are better place for everyone.

**Comment by Fortifier42** [comment]
I can't actually find an up to date Survival Games plugin that is free.. Most have gone premium on spigot.org.

**Comment by Fortifier42** [comment]
Closing due to unable to get a maintained and free plugin.
