### ISSUE TITLE
Skyblock Support

### ISSUE THREAD

**Issue by mcmonkey4eva** [DenizenScript/Depenizen-For-Bukkit#37]
Support a skyblock plugin, any of 'em, pls.

REQUESTED:
`- skyblock create [whatever arguments the system allows, EG schematic choice]` create a new skyblock for the linked player
`- skyblock delete [skyblock thingy]`
`<player.skyblocks>` a list of all skyblocks a player has - including the skyblock's location and whatever other info (EG, schematic choice) + list of allowed players
`<server.skyblocks>` a list of all skyblocks that exists, including details above + owner

**Comment by Fortifier42** [comment]
In regards to the command, Currently investigating what options are available. Having trouble finding a clean cut creatSkyblock (or similar) method, they all are command based... :(

**Comment by mcmonkey4eva** [comment]
luckily we have `- execute` -- I'm calling this complete :)
