### ISSUE TITLE
ChessCraft link

### ISSUE THREAD

**Issue by mcmonkey4eva** [DenizenScript/Depenizen-For-Bukkit#38]
We control chesscraft, tell me if you need anything to fully enhance a chesscraft link.

- ability to create and control chessboards
- events for chess game completion (including winner/loser), ...

**Comment by Morphan1** [comment]
So there seems to be 2 newer unofficial forks of ChessCraft, but both are likely to be questionably maintained so I'm going to declare the plugin as dead. RIP
