### ISSUE TITLE
broken .region tags

### ISSUE THREAD

**Issue by KeangDavid** [DenizenScript/Depenizen-For-Bukkit#40]
Region tags are returning with the tag and creating an internal error. This has persisted through multiple updates. I have done all the debug/troubleshooting I can think of. I made sure to update I have tried the latest dev and main builds of denizen.

dScript: /ex narrate
Server Log: http://mcmonkey.org/paste/12719

Summery of error:

    Start server
    log on
    type: /ex narrate
    returns "player.location.regions"
    get internal error
    log out

Are you even in a region? Yes.

**Comment by TehNinth** [comment]
I may have found some code that may or may not help this issue:

http://xikage.elseland.net/viewgit/?a=viewblob&p=MythicMobs&h=a7ab1caadcb6018e9fe74dadf8ed9d5a4e81cd69&hb=HEAD&f=MythicMobs/src/net/elseland/xikage/MythicMobs/Compatibility/WorldGuardSupport.java
to be compared with
http://github.com/DenizenScript/Depenizen-For-Bukkit/blob/master/src/main/java/net/gnomeffinway/depenizen/support/plugins/WorldGuardSupport.java

**Comment by mcmonkey4eva** [comment]
@TehNinth  how is that relevant 0.o

**Comment by KeangDavid** [comment]
He's just trying to help. A little update; I am having the issue using Spigot as well.
