### ISSUE TITLE
Towny - events & new tags

### ISSUE THREAD

**Issue by michalet** [DenizenScript/Depenizen-For-Bukkit#41]
Would it be possible to add even triggers for towny?

Something like this:
**on player enters/leaves [town]**
**context:** player, town name, nation name (if any), town's board, capital (town is a nation capital - true/false)
maybe even **determine:** string (to replace towny's message)

Edit: new tags would be amazing as well:

\<town@town.outposts>
returns number of outposts of the town, 0/false if no outposts

**Comment by Fortifier42** [comment]
Closing in favour of https://github.com/DenizenScript/Depenizen-For-Bukkit/issues/54
