### ISSUE TITLE
Depenizen errors registering flags

### ISSUE THREAD

**Issue by michalet** [DenizenScript/Depenizen-For-Bukkit#42]
After updating to Depenizen build 235, there are some errors on startup. Haven't had the time to test much, but  flag <t@[town_name].size> throws an error "Invalid object type! Could not fetch 'town'!", but eg. <player.town.name> works fine.
Error log: http://pastebin.com/qk1i1Lpd
Server version: git-Spigot-fa7cbf9-59dd2dd (MC: 1.8) (Implementing API version 1.8-R0.1-SNAPSHOT)

**Comment by mcmonkey4eva** [comment]
Update Denizen.

**Comment by michalet** [comment]
Sorry for not writing that in the first post, but it's happening on latest build (1560).

**Comment by calico-kid** [comment]
try the dev build of denizen

**Comment by michalet** [comment]
I suppose you don't mean the one from ci.citizensnpcs.co? Where can I get it if so?

**Comment by calico-kid** [comment]
join us in the denizen-dev on esper and we can get ya a link there. also i will show you how to grab latest build links from there

**Comment by Dopplizzle** [comment]
I am getting an almost identical error, using Denizen dev-build 110 and Depenizen build  235, only it's "Failed to register an object type (WorldGuardRegion)." Still seems to works, though, as far as I can tell.
Error log: http://pastebin.com/sm9sfk7N

**Comment by michalet** [comment]
Even latest dev build (110) gets me the same errors. So far looks like mcMMO and Denizen hook fine, but towny and worldguard throw errors.

**Comment by mcmonkey4eva** [comment]
@michalet - Does the patch Morph submitted above ^ fix it?

**Comment by michalet** [comment]
Denizen build 1561 & depenizen build 236, no errors. Thank you for the fix.
