### ISSUE TITLE
TagManagerObjectReflection error thrown in dev-build 129

### ISSUE THREAD

**Issue by Dopplizzle** [DenizenScript/Depenizen-For-Bukkit#43]
`<el@val[100].sub[1]>` works fine, but `<el@val[100].sub[0]>` throws the error.

(same issue with `<el@100.sub[0]>`)

Reporting as requested by the error.

**Comment by mcmonkey4eva** [comment]
My bad, I trusted morphan by accident. Fixed.

Also why in space is this in the Depenizen issue page?

**Comment by Dopplizzle** [comment]
Ummmm...because I am a complete moron and clicked the wrong shortcut and didn't see it until right this second?

Anyhoo, thanks again.
