### ISSUE TITLE
Heroes InCombat

### ISSUE THREAD

**Issue by johndcastro** [DenizenScript/Depenizen-For-Bukkit#44]
It would be helpful to be able to check if the player is in combat.

In Heroes the reference we are looking for is hero.isInCombat() (which returns true or false)

Thanks for looking.

**Comment by johndcastro** [comment]
For anybody interested I added this to the HeroesHeros.java class:

        if (attribute.startsWith("incombat")) {
            //return new Element(hero.isInCombat()).getAttribute(attribute.fulfill(1));
            if (hero.isInCombat()) {
                return new Element("Yes").getAttribute(attribute.fulfill(1));
            }
            else {
                return new Element("No").getAttribute(attribute.fulfill(1));
            }
        }

**Comment by Morphan1** [comment]
Strange... I don't think I ever saw this issue :confused: I'll add proper code for this into Depenizen in a few hours

**Comment by johndcastro** [comment]
Thanks.

Could I trouble you for a command for hero parties?  I.e. -heroes addparty <player object heroes> <target player object heroes>
