### ISSUE TITLE
TerrainControl

### ISSUE THREAD

**Issue by NLBlackEagle** [DenizenScript/Depenizen-For-Bukkit#45]
Hello, I would like to request tag support for terraincontrol biome names
As example, being ingame If type /tc biome to get the current biome name ( Which is a implented feature of TerrainControl ) I get the correct biome I'm standing in at that moment. Sadly this doesnt works for the denizen tags at all.

Here's the API: https://github.com/MCTCP/TerrainControl/wiki/Developer-page

I would like this tag to support TerrainControl:
<player.location.biome.formatted>

Thanks in advance!

**Comment by KsenMih** [comment]
:+1:

**Comment by Morphan1** [comment]
I added `<l@location.tc_biome.name>`, if you need anything else, just reply

**Comment by NLBlackEagle** [comment]
Woah! manyyy <3'sss! Thanks :D
