### ISSUE TITLE
Broken region tags.

### ISSUE THREAD

**Issue by KeangDavid** [DenizenScript/Depenizen-For-Bukkit#47]
Problem:
<code>/ex narrate \<player.location.regions.get[1].owners\></code> and <code>/ex narrate \<player.location.regions.get[1].members\></code> are returning with <code>li@</code> regardless or owners or members.

Steps to reproduce problem:
1. Stand in region with a owner.
2. Type <code>/ex narrate \<player.location.regions.get[1].owners\></code>

Log: http://mcmonkey.org/paste/14566
Screenshot: https://dl-web.dropbox.com/get/2015-03-18_03.22.24.png?_subject_uid=276334414&w=AAAxnsHiIAhwaYeulyYv0C8hFeFMxyED3goG3dOMgGJiZQ

Updated with cleaner log.

**Comment by mcmonkey4eva** [comment]
What is `player.locations.regions.get[1]` are you sure it's not `__global__` or somethin'?

**Comment by KeangDavid** [comment]
What? http://mcmonkey.org/denizen/tags/regions

**Comment by mcmonkey4eva** [comment]
... I meant what does the tag return, genius. Read my post, all of it, not just the first part.

**Comment by KeangDavid** [comment]
Regions it suppose to list the regions a location is in. That is why I put a link to what it is suppose to do. I actually made it through the entire sentence of your post. I just don't understand why you think __global__ would do anything.

**Comment by Fortifier42** [comment]
@mcmonkey4eva We use these tags, so I assume this is fixed? O.o
