### ISSUE TITLE
MobArena

### ISSUE THREAD

**Issue by Mwthorn** [DenizenScript/Depenizen-For-Bukkit#52]
MobArena (http://dev.bukkit.org/bukkit-plugins/mobarena/) has been on of the most used PvE plugins out there. It would be cool to create Denizen support to allow more use of the arenas. 
My idea was of having a NPC give a quest to compete in a MobArena, then maybe give the player goals such as getting to a specefic wave or kill a certain amount of monsters in the arena.
Other ideas are listed at the buttom. As for rewards it could be unlocking new arenas or classes.

It would be cool to add events such as:
"on mobarena start  (in \<arena name\>)"
"on mobarena finish  (in \<arena name\>)"
"on mobarena next wave (in \<arena name\>)"

Then maybe have context like:
"\<context.arena\>" returns the name of the arena
"\<context.wave\>" returns the current wave they are/ended on (as an integer?)
"\<context.players\>" returns a dList of players who are/were in the arena

Also maybe tags such as:
"\<ma_status[\<arena name\>]" checks the staus on a arena, could be OPEN, CLOSED or RUNNING
"\<ma_spawners[\<arena name\>]\>" returns a list of dLocations of spawners (for wave spawning)
"\<ma_lobby_enter[\<arena name\>]\>" returns the dLocation of the lobby teleport spot
"\<ma_arena_enter[\<arena name\>]\>" returns the dLocation of the arena teleport spot
"\<ma_arenas\>" returns a list of all arenas
"\<ma_in_arena[\<arena name\>]\>" returns a dlist of players in the arena
"\<p@player.ma_lastarena\>" returns the name of the arena the player last arena played on
"\<p@player.ma_lastwave\>" returns the last wave the player ended on from last arena
"\<p@player.ma_damageDone\>" returns how much damage the player dealt from last arena
"\<p@player.ma_damageTaken\>" returns how much damage the player took from last arena
"\<p@player.ma_kills\>" returns how many kills the player got from last arena
"\<p@player.ma_class\>" returns the class name the player used from last arena

Finally some examples for use could be:
    on mobarena finish:
    - if \<context.wave\> \> \<server.flag[ma_highestwave]> {
        - announce "The record on \<server.flag[ma_highestwave]> waves was beaten with \<context.wave\> waves cleared!"
        ## Give bonus rewards to \<context.players\> or save them in a flag for later use
    }
   
Another example but with use of npc interact:
- if \<player.ma_class\> == "Archer" && \<player.ma_lastwave\> \> 10 {
     - chat "You seem pretty good with your skills as an archer. Want to join our Ranger Clan?"
}

**Comment by Talamar1** [comment]
API/Event calls:
https://github.com/garbagemule/MobArena/tree/bleeding/src/com/garbagemule/MobArena/events

**Comment by kain184** [comment]
i would have to agree with the inclusion of this in the future. i have been looking for just this everywhere as i have functions i want to use in the normal denizen system such as signs that update with information about the arenas. and these functions are a must for many server users in my opinion other functions that i would look forward to seeing is the ability for mob arena to call on scripted npcs through spawning by using something like. if <mobarena.wave> == x - spawn n@npc - assign script npc allowing for boss battles that are completely scripted. also allowing for control of the arena with items. for the survival map that my friends and i are creating in mob arena the abilities are endless. and i would greatly appreciate this going forward.

**Comment by Fortifier42** [comment]
I'm looking into this as we speak, I need to move a few things around (as we already have an "arena" for pvparena)!

**Comment by Fortifier42** [comment]
[x] - Add mobarena object
[] - Populate object with tags
[] - Add player extension
[] - Add events

**Comment by Fortifier42** [comment]
Finished so far, needs a lot of testing.
