### ISSUE TITLE
compatibility Jobs Reborn

### ISSUE THREAD

**Issue by drAkeTool** [DenizenScript/Depenizen-For-Bukkit#53]
Hi guys.

is possible update the plugin "jobs v2.12.0" that no longer updated more
http://dev.bukkit.org/bukkit-plugins/jobs/
to the plugin "Jobs reborn"
http://dev.bukkit.org/bukkit-plugins/jobs-reborn/

since loading the plugin "Jobs reborn" the depenizen plugin gives errors for some reason :(

thanks for watching and sorry for my bad english.

**Comment by Fortifier42** [comment]
I think this was fixed :)

**Comment by mcmonkey4eva** [comment]
Yup!
