### ISSUE TITLE
Towny events

### ISSUE THREAD

**Issue by doomlordking** [DenizenScript/Depenizen-For-Bukkit#54]
Can you can a denizen tag for a player towny modes <li@player.modes>

In towny you can toggle modes like spy/plotborder/map and the townychat saves what channel you do in there to. it looks like (mode,mode,etc)

With this tag you can check if someone is in a townychat channel and do stuff "if in local this do whatever"

**Comment by doomlordking** [comment]
"michalet" idea of adding on player enters/leaves [town] would be awesome too. On enter, -title "welcome to <town>" :) 
https://github.com/DenizenScript/Depenizen-For-Bukkit/issues/41

**Comment by Fortifier42** [comment]
I'll look into these, sorry for it taking so long guys :)

**Comment by Fortifier42** [comment]
Please note, we are unable to cancel or determine a new message from towny, so I have not added the ability to. These events are **NOT** cancellable and are documented as such. In regards to #41, The nation can be found by using `<town@town.nation>` and as such a context would be useless.

Am awaiting testing on these.

**Comment by Fortifier42** [comment]
Towny chat is a separate plugin all together and I will add tags for these separately.
