### ISSUE TITLE
Trouble with connecting multiple servers using socket

### ISSUE THREAD

**Issue by Mwthorn** [DenizenScript/Depenizen-For-Bukkit#55]
When I try to connect the to the bungee network. I can only be able to connect one of them.
This is what I get from the bungee log:
http://mcmonkey.org/paste/20601
I have the following setup on the configs:
Bungee: http://mcmonkey.org/paste/20604
Lobby: http://mcmonkey.org/paste/20603
Creative: http://mcmonkey.org/paste/20602

How can I connect them all together?
My guess would be to add multiple port networks on the bungee config...

**Comment by Morphan1** [comment]
Try changing `Timeout: 3000` to `Timeout: 0`

**Comment by Mwthorn** [comment]
That works! Everything looks good :)
