### ISSUE TITLE
Possible to add attributes using nbteditor's API?

### ISSUE THREAD

**Issue by Mwthorn** [DenizenScript/Depenizen-For-Bukkit#56]
This is more of a question, is it possible to add nbteditor's API taking a part of it for use in Denizen?
http://dev.bukkit.org/bukkit-plugins/nbteditor/?page=8

Thinking it would be nice to have it in the scripts for example:

ScriptName:
type: item
material: wood_sword
name: Swift Sword
Attributes:
- MovementSpeed: 0.5
- AttackDamage: 2.0

**Comment by Morphan1** [comment]
There's no reason for this. Anything you can do with that plugin would be easier to add to Denizen itself.

**Comment by Mwthorn** [comment]
So... should I go and put it on the Denizen's issue and suggest it there?

**Comment by Morphan1** [comment]
Yes, and preferably open 1 issue per request, being specific for each thing rather than encompassing it all in one issue
