### ISSUE TITLE
Bungee timeouts are weird

### ISSUE THREAD

**Issue by mcmonkey4eva** [DenizenScript/Depenizen-For-Bukkit#58]
`Try changing Timeout: 3000 to Timeout: 0` - Morphan1

This fixes https://github.com/DenizenScript/Depenizen-For-Bukkit/issues/55

**WHY**

This should be fixed, either by figuring out what's wrong OR changing the default value.

**Comment by Morphan1** [comment]
Probably due to being sync, remind me to look into this later

**Comment by Fortifier42** [comment]
**look into it now pls**

**Comment by Morphan1** [comment]
@Fortifier42 I'm in school right now m8, remember time zones

**Comment by Morphan1** [comment]
The above commit MIGHT fix the problem.
That or make it worse. I can't really test it, tell me how it goes :heart:

**Comment by Fortifier42** [comment]
This still a thing?
