### ISSUE TITLE
Bungee: Server list, current server

### ISSUE THREAD

**Issue by mcmonkey4eva** [DenizenScript/Depenizen-For-Bukkit#59]
`<bungee.server>` returns the current server.
`<bungee.list_servers>` returns all servers, including the current.

Also, you don't currently even register the current server as a dServer -> that needs to be fixed!

**Comment by mcmonkey4eva** [comment]
Also, only register bungee support if bungee is actually loaded maybe? @.@

**Comment by Morphan1** [comment]
What do you mean "don't currently register the current server as a dServer"?
And Bungee support is only used if you turn it on in your config, beyond that isn't our problem.

**Comment by mcmonkey4eva** [comment]
`And Bungee support is only used if you turn it on in your config`
Cannot find evidence of this in the code - where's it do that check?
`What do you mean "don't currently register the current server as a dServer"?`
`Server1` can't do `server@Server1`

**Comment by Talamar1** [comment]
Line 91 in Depenizen.java:
```
        if (Settings.socketEnabled()) {
```

**Comment by mcmonkey4eva** [comment]
That's not relevant.

**Comment by Morphan1** [comment]
That is, in fact, relevant

**Comment by Morphan1** [comment]
`Server1 can't do server@Server1`
Why would you ever need to do that?

**Comment by mcmonkey4eva** [comment]
```
        getServer().getMessenger().registerOutgoingPluginChannel(this, "BungeeCord");
        getServer().getMessenger().registerIncomingPluginChannel(this, "BungeeCord", this);
        new BungeeCommand().activate().as("BUNGEE").withOptions("bungee", 1);
        ObjectFetcher.registerWithObjectFetcher(dServer.class);
        DenizenAPI.getCurrentInstance().getPropertyParser()
                .registerProperty(BungeePlayerExtension.class, dPlayer.class);
        ScriptEvent.registerScriptEvent(new ProxyPingScriptEvent());
```
this entire block runs regardless of Bungee being enabled.

**Comment by Talamar1** [comment]
To do this:
```
    on player chats:
    - if <context.message.starts_with[~].not> queue stop
    - define server <server@server.name>
    - define player <player.name.display>
    - define msg <context.message.replace[firstregex:^~]>
    - bungee all {
      - announce "<&rb>%server%<&lb><&rb>%player%<&lb> %msg%"
      }
```

**Comment by Talamar1** [comment]
Don't worry, I will rewrite it all in bungee.* speak and make it all buggy and shit

**Comment by Morphan1** [comment]
Fixed in recent commits
