### ISSUE TITLE
Jobs fixing

### ISSUE THREAD

**Issue by mcmonkey4eva** [DenizenScript/Depenizen-For-Bukkit#61]
Jobs needs to be updated to Jobs Reborn, not the original Jobs. Jobs is dead.

Or, we could drop it if nobody wants it.

It's literally causing bugs to have Jobs reborn on a Depenizen server.

**Comment by Morphan1** [comment]
I'll do this soon if you don't magically pull it together yourself
For now, I may have stopped the errors from Jobs Reborn from killing all of Depenizen
