### ISSUE TITLE
placeholders :)

### ISSUE THREAD

**Issue by drAkeTool** [DenizenScript/Depenizen-For-Bukkit#62]
Good day to all!

I have a suggestion to this great plugin
There is possibility of adding denizen placeholders?

This API is very interesting hurts me that I am not a programmer :(
https://www.spigotmc.org/resources/placeholderapi.6245/

the idea is that you can create placeholders denizen of the flags that would be great to put it in other plugins as holograms tablist etc etc.

it's just a suggestion, I hope to be valued.
Thank you for reading.

(I use google translator jeje sorry for my bad english)

**Comment by mcmonkey4eva** [comment]
You want us to... hook some random API as a more generic hook for a pile of other plugins? Could be interesting...

**Comment by Fortifier42** [comment]
So what exactly is the request here? The ability to /create/ placeholders?

**Comment by mcmonkey4eva** [comment]
@Fortifier42 that and read them.

**Comment by Morphan1** [comment]
I've added support for this. To get Denizen information via placeholders you can use `%denizen_<Denizen Tag Here>%`.

 For example, if you want to get a linked player's name, you could use `%denizen_<player.name>%`. Magic!

 You can also use non-player tags. If you want the version of the server for whatever reason, you could use `%denizen_<server.version>%`.

Obviously, this allows you to get information such as flags in a familiar way: `%denizen_<player.flag[FlagName]>%`, `%denizen_<server.flag[FlagName]>%`, etc.

You can also get other plugin placeholder information in Denizen with the tag `<placeholder[<insert placeholder here>]>`. 

For example, if you wanted to retrieve the placeholder `%heroes_main_class_name%`, you could use `<placeholder[heroes_main_class_name]>` (note the lack of % symbols there!)
