### ISSUE TITLE
<server.match_bungee_player[<name>]>

### ISSUE THREAD

**Issue by Fortifier42** [DenizenScript/Depenizen-For-Bukkit#63]
Great to have a tag to find a player anywhere on the bungee network? :+1: 

Could return a dPlayer or simply the server the player is on.

**Comment by mcmonkey4eva** [comment]
What would it return? dPlayer isn't necessarily valid.
If we add this, also need `<server@server.list_players>` and `<server@server.match_player>` and all sorts of crazy stuff like that.

**Comment by Fortifier42** [comment]
I mentioned this on the IRC, the ability to send player data between servers on the socket, would be handy. In a sense, synchronize or at least allow fetching of information from other servers.
