### ISSUE TITLE
[bungee] Ability to syncronise notables/flags cross-server

### ISSUE THREAD

**Issue by Fortifier42** [DenizenScript/Depenizen-For-Bukkit#64]
It would be good if notables/flags etc could be syncronised across servers.

This would be the best thing to ever happen to Depenizen (for bungee).
This, or allow flags/notables to have a different storage method. e.g. Redis, SQL

**Comment by Morphan1** [comment]
Hmm... What's the difference between this and using #50?

**Comment by mcmonkey4eva** [comment]
power to #50

**Comment by Fortifier42** [comment]
Persistence, and also wouldn't rely on bungee, if they didn't want to. Keeping things in sync over different servers becomes easier again!

**Comment by Morphan1** [comment]
I think this should be the job of a script. I don't like the idea of automatically editing the saves.yml of multiple servers like that.

**Comment by Fortifier42** [comment]
With bungeetag fixed, this isn't so much a problem anymore!
