### ISSUE TITLE
Definitions do not parse with bungeetag

### ISSUE THREAD

**Issue by Fortifier42** [DenizenScript/Depenizen-For-Bukkit#65]
script: http://mcmonkey.org/haste/22849
debug: http://mcmonkey.org/paste/22848

**Comment by Morphan1** [comment]
@Fortifier42 are both servers up-to-date with all dRelated plugins?

**Comment by Fortifier42** [comment]
Everything. I pestered you about this issue when you first made the changes, and still nothing

**Comment by Morphan1** [comment]
What debug is there for the server sending the bungeetag command? You failed to post that

**Comment by mcmonkey4eva** [comment]
@Morphan1 I'm guessing he bungeetag'd his own current server for the sake of capturing all the debug?

**Comment by Fortifier42** [comment]
Why should I have an if statement to check if the player is on the server? Shouldn't I be able to universally use bungeetag regardless of which server the player/script is running from?

**Comment by Fortifier42** [comment]
For the sake of showing that it is not because I am using bungeetag on the same server as it is running:

Run on Creative - debug: http://mcmonkey.org/paste/22895
Bungeetag'd to Lounge - debug: http://mcmonkey.org/paste/22896

**Comment by Morphan1** [comment]
Should be fixed by 3e8bacf
Curse you and your capitalized letters!
