### ISSUE TITLE
Give heroesxp

### ISSUE THREAD

**Issue by o0ower0o** [DenizenScript/Depenizen-For-Bukkit#68]
Hi, I'm reposting this ticket from the Denizen project:
https://github.com/DenizenScript/Denizen-For-Bukkit/issues/1250
So basically a command with this syntax would be good:
`- heroesexp (<player>) qty:# [primary/secondary]`

If prim/second is not specified then the exp goes to the primary class.

**Comment by Fortifier42** [comment]
Hi @o0ower0o - I read your Denizen ticket, if you wish to hide command output, you can use the `silent` argument on the `- execute` command.

I can/will start working on adding Heroes commands to Depenizen for you - but until such time I recommend using the execute command still :)

**Comment by o0ower0o** [comment]
Thank you!

**Comment by Fortifier42** [comment]
This was added in the latest builds :)
http://ci.citizensnpcs.co/job/Depenizen/287/
