### ISSUE TITLE
Add essentials vanish tag

### ISSUE THREAD

**Issue by Mwthorn** [DenizenScript/Depenizen-For-Bukkit#70]
A tag to check if a player is in vanish from Essentials.
The tag could be <p@player.is_vanish>

**Comment by Fortifier42** [comment]
https://github.com/ausFort/Depenizen-For-Bukkit/commit/82900a9d91937eec99ad1ede30e797d19f768fd0

I added this - waiting on @Morphan1 to accept my PR, eventually.
