### ISSUE TITLE
PlotMe support

### ISSUE THREAD

**Issue by Talamar1** [DenizenScript/Depenizen-For-Bukkit#71]
Plotme github: https://github.com/WorldCretornica/PlotMe-Core
Example Plugin support: https://github.com/WorldCretornica/PlotMeHookExample

Would like to see things like:
```
<player.plots> - returns a list of plots owned by player
<player.has_plots> - returns boolean if player owns any plots
<location.plot> - returns the plot entity/id of the location (or null)
<plot.owner> - returns the player object of the owner of the plot
<plot.id> - returns the id of the plot
<plot.cuboid> - returns the cuboid of the plot
<world.isPlotWorld> - returns boolean of whether or not the world was PlotMe generated
```
In the future, could add functionality to modify plots, like owner, properties, etc.

**Comment by Fortifier42** [comment]
PlotMe has been discontinued.

https://www.spigotmc.org/resources/plotme-official.2131/

Recommend support for PlotSquared instead.

**Comment by Talamar1** [comment]
https://www.spigotmc.org/threads/plotme-official.37327/page-114
The author is looking to bring it back, there are 2 other authors maintaining the current code.
And the last release was downloaded almost 13.6K times.  PlotSquared is buggy as hell and people don't like it (only 1200 downloads on the last release).
Given that Towny was archived (exists under a new project now), Votifier,Jobs, Prism, PvPArena and PvP-Stats haven't been updated since 1.7.9, McMMO is on 1.8.1.  I don't see it being out of the realm of question to ask for it.

**Comment by mcmonkey4eva** [comment]
Initial attempt ready, need testing and potentially refining.

**Comment by Talamar1** [comment]
Preliminaries are done, will request more as needed.  Thank you.
