### ISSUE TITLE
SimpleClans Support

### ISSUE THREAD

**Issue by CorporalBruno** [DenizenScript/Depenizen-For-Bukkit#72]
Thanks. Hugs & Kisses - Zaphod

- Kill /Death ratio of each player, clan, etc
- clan names, tags, members, resources, locations
- clan list over all
- clans at war
- clans verified
- clans not verified
- clans allied

**Comment by Fortifier42** [comment]
Started working on this, will post updates as they come. :)

So far - initialised and working on clan object, added a few tags.

**Comment by Fortifier42** [comment]
Think I covered all that I can, wasn't sure what you meant by resources and locations.

**Comment by CorporalBruno** [comment]
simpleclans kill death ratio returns 0.0 when in reality it was 3.2
