### ISSUE TITLE
event's Heroes no works

### ISSUE THREAD

**Issue by drAkeTool** [DenizenScript/Depenizen-For-Bukkit#75]
on hero changes level:
on hero changes experience:

please fix it :D
and thanks for the help

Denizen #1605
Depenizen #280

**Comment by mcmonkey4eva** [comment]
... any errors?... anything?

**Comment by mcmonkey4eva** [comment]
also try using `denizen debug -e` to see if they fire at all

**Comment by drAkeTool** [comment]
I no have no errors in the console
because no detects the event

this is my script:
http://mcmonkey.org/paste/27804

but nothing happens when my character changes level

**Comment by mcmonkey4eva** [comment]
Please try `denizen debug -e` and post a debug recording of what happens when theres a hero level change

**Comment by drAkeTool** [comment]
Ok try using the command

But I do not detect any event in the console associated with heroes
I detected others that I have, but none with heroes

I try to get a level with the command:
"admin hero level <player.name> <player.heroes.primary_class.name> 200"
and also killing mobs.

when changing level there is no event that detects the debugg
http://mcmonkey.org/paste/27805

Sorry for my bad english

**Comment by mcmonkey4eva** [comment]
Are you leveling up legitimately or just using commands 0.o

**Comment by mcmonkey4eva** [comment]
That is odd.

**Comment by mcmonkey4eva** [comment]
@Morphan1 what's going on here?

**Comment by mcmonkey4eva** [comment]
@drAkeTool Looks like they weren't even being registered! @Morphan1 `>:(` so try build 281 and see if that fixes it?

**Comment by drAkeTool** [comment]
Perfect the problem is resolved

#281 denizen it's good

**Comment by mcmonkey4eva** [comment]
Yay!

**Comment by Morphan1** [comment]
Oops
