### ISSUE TITLE
SimpleClans Tags not returning proper values

### ISSUE THREAD

**Issue by CorporalBruno** [DenizenScript/Depenizen-For-Bukkit#77]
/ex narrate <p@playername.simpleclans.kills.neutral>
returns 0

/clan lookup playername 
returns 137

Many tags do this.

**Comment by Fortifier42** [comment]
Simpleclans issue, We simply call their methods. Update your simpleclans.

**Comment by CorporalBruno** [comment]
no update available. running latest version of everything.

tag: player.simpleclans.clan returns the players UUID not clan name.

tag: clan.kill_death_ratio returns 0.0 (error)

tag: clan.kills.civilian works
tag: clan.deaths works

**Comment by Fortifier42** [comment]
Just fixed those issues, and added a ~~few~~ lot of new tags, which I hope will be satisfactory.

**Comment by Fortifier42** [comment]
@CorporalBruno Mr Morphan1 will need to accept my Pull Request so that all my fixes and improvements go in - harass him if you need to ;)
