### ISSUE TITLE
Incorrect paste schematics?

### ISSUE THREAD

**Issue by drAkeTool** [DenizenScript/Depenizen-For-Bukkit#87]
I have some scripts with this code to regenerate a resource zones
but with the new build of depenizen they were broken

fails to paste the schematic on the location
I read this change in build 284
"Remove WorldEdit's schematic command ... finally"

This is why it broke?
if so, what is the alternative
```
   - ^schematic load name:rulbertfrst
   - ^schematic paste name:rulbertfrst location:3049,111,3175,Esparcraft noair
   - ^schematic unload name:rulbertfrst
```
Srry for my bad english
depenizens test: 291
denizen test: 1606

**Comment by Fortifier42** [comment]
Hey drake!

Basically, the schematic command provided by Depenizen used WorldEdit's schematic tools. We've replaced that internally in Denizen with what @mcmonkey4eva describes as a better and more efficient alternative. The new syntax for the schematic command is as follows:
```
schematic: Creates, loads, pastes, and saves schematics (Sets of blocks).
Syntax: - schematic [create/load/unload/rotate/paste/save] [name:<name>] (angle:<#>) (<location>) (<cuboid>) (delayed)
```

**Comment by mcmonkey4eva** [comment]
@Fortifier42 it's not designed to be better or more efficient, it's just a version that doesn't need worldedit to work.

**Comment by drAkeTool** [comment]
Ok I understand, but could not know what the correct syntax to accommodate my scripts

for example, in this script
what is the syntax?

   - ^schematic load name:rulbertfrst
   - ^schematic paste name:rulbertfrst location:3049,111,3175,Esparcraft noair
   - ^schematic unload name:rulbertfrst

**Comment by drAkeTool** [comment]
as well as this you paste the schematic
but not in the right location

**Comment by Fortifier42** [comment]
I'd imagine `- ^schematic paste name:rulbertfrst l@3049,111,3175,Esparcraft`

Since your load and unload lines look fine.

**Comment by drAkeTool** [comment]
apparently the command paste the schematic, at the point where you start the schematic

rather than the previous system guarding the location where it was created
right?

**Comment by Fortifier42** [comment]
That seems to be correct @drAkeTool  :)

**Comment by drAkeTool** [comment]
Just one more question

if I think the schematic in a cuboid is possible to save the schematic in the same location

and paste using the same value?

for instance:
Create
    - schematic create name:rulbertfrst cu@bosquemes location:cu@bosquemes
    - schematic save name:rulbertfrst

Paste
    - ^schematic load name:rulbertfrst
    - ^schematic paste name:rulbertfrst cu@minameslajho
    - ^schematic unload name:rulbertfrst

or what would be the right way

**Comment by mcmonkey4eva** [comment]
use either a corner or the center of the cuboid as the location

**Comment by drAkeTool** [comment]
You could be used as the center of the schematic as location?

**Comment by Fortifier42** [comment]
To create the schematic you'd use:
```
- schematic create name:name cu@cuboid l@x,y,z,world ## Where the cuboid is the region saves, and the location is the ORIGIN (the location the schematic is pasted from)
- schematic save name:name
```

Once you've saved it, you'd use the creation location as the reference, remember this is where the schematic pastes from.

@drAkeTool yes, you can. Just create the schematic with the origin location as the centre.

**Comment by drAkeTool** [comment]
ok I understand, I just would like to know how the syntax of the location if to stick it in a corner of a cuboid

**Comment by Fortifier42** [comment]
You'd want to use the `<cu@cuboid.min>` or `<cu@cuboid.max>` tags.
```
- define Cuboid cu@x,y,z,world|x2,y2,z2,world
- schematic create name:name <def[cuboid]> <def[cuboid].max/min>
```

**Comment by drAkeTool** [comment]
Perfect tnks
