### ISSUE TITLE
Heroes heroesxp "add"

### ISSUE THREAD

**Issue by drAkeTool** [DenizenScript/Depenizen-For-Bukkit#92]
heroes command to add experience seems to be broken
it does not add more experience working as a set

If I run this command several times does not change the experience
"- heroesxp add Vampiro quantity:10"

Srry for my bad english
http://mcmonkey.org/paste/28708

**Comment by Fortifier42** [comment]
I'm looking into this! :)

**Comment by Fortifier42** [comment]
It would seem that the XP is being set. Going to try figure out why.

**Comment by Fortifier42** [comment]
Fixed :D
