### ISSUE TITLE
vulnerable tag gives incorrect value

### ISSUE THREAD

**Issue by Croat** [DenizenScript/Depenizen-For-Bukkit#94]
npc.vulnerable will return true when the npc is invincible, and false when he is vulnerable.
In my Denizen configuration, damage is disabled by default.The error may or may not occur when damage is enabled by default, as I haven't tested it.

**Comment by Fortifier42** [comment]
Wrong place, however it is because we don't reverse the value.. It seems to be trying to return whether it is INVULNERABLE not VULNERABLE

**Comment by mcmonkey4eva** [comment]
Tag renamed to reflect its return value.
