### ISSUE TITLE
Plugin hooks idea

### ISSUE THREAD

**Issue by doomlordking** [DenizenScript/Depenizen-For-Bukkit#96]
List of some Plugin with would be useful for Depenizen

1. Shopkeepers (has some citizen support)
Ability to add/remove/edit trades
http://dev.bukkit.org/bukkit-plugins/shopkeepers/
https://github.com/nisovin/Shopkeepers

2. ban-management (doesn't use defualt ban.json file)
http://dev.bukkit.org/bukkit-plugins/ban-management/

**Comment by Fortifier42** [comment]
Sorry what?

**Comment by doomlordking** [comment]
i posted hit enter before editing sorry

**Comment by Fortifier42** [comment]
I'll need to know exactly what you'd like from each to be added. E.g. what events, tags, or commands you would like implemented :)

**Comment by doomlordking** [comment]
Ban-Management
Uses mysql to store data. (Doesn't use banned-players.json)
http://dev.bukkit.org/bukkit-plugins/ban-management/pages/commands-permissions/

(/tempban & /ban)
<p@player.is_banned> - Check if banned
<p@player.ban_info.expiration> - How long a tempban has left
<p@player.ban_info.reason> - Reason for banned
<p@player.ban_info.created> - Who banned player
<server.list_banned_players> - List of banned players

(/tempmute & /mute)
<p@player.is_muted> - Check if muted
<p@player.mute_timeout> - How long a tempmute has left
<p@player.mute_info.reason> - Reason for mute
<server.list_muted_players> - List add muted players

(/warning)
<p@player.warning.list> - List warns are player has

ShopKeeper
Mostly want cmd to set trades of vilalger/npcs
Tags get trades i guess
http://nisovin.com/shopkeepers/shopkeeper_admin_editor.png

**Comment by Fortifier42** [comment]
I can see a lot of conflictions with this, e.g. we already have most of these tags.

Will consider ban manager. Will look into ShopKeepers however.

**Comment by Morphan1** [comment]
Is ban manager support still wanted?
Also, we have some ShopKeepers support, though I'm not sure what still needs to be done there.
If you're still interested, we could finish up support for both plugins

**Comment by doomlordking** [comment]
Not really :) just needed the shopkeeper the most, I works greats thanks.
