### ISSUE TITLE
Skillapi Tags

### ISSUE THREAD

**Issue by drAkeTool** [DenizenScript/Depenizen-For-Bukkit#98]
I have some suggestions for skillapi plugin tags

```
<skillapi.class>
<skillapi.class.level>
<skillapi.class.xp>
<skillapi.mana>
<skillapi.mana.name>
```

thanks for read :)

**Comment by Morphan1** [comment]
Strange. I thought I did this forever ago... It was part of the first SkillAPI request. @Fortifier42 will probably do this before I even get home :smile_cat:

**Comment by Fortifier42** [comment]
@Morphan1 considering it was 1-2am, no I wouldn't have D:

**Comment by Fortifier42** [comment]
Seems that SkillAPI has got the better of me... @Morphan1 Your turn :cry: :heart:
